/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input signed [63:0] eta_0_0_0
    , input signed [63:0] eta_0_0_1
    , input signed [63:0] eta_0_0_2
    , input signed [63:0] eta_0_0_3
    , input signed [63:0] eta_0_0_4
    , input signed [63:0] eta_0_0_5
    , input signed [63:0] eta_0_0_6
    , input signed [63:0] eta_0_0_7
    , input signed [63:0] eta_0_1_0
    , input signed [63:0] eta_0_1_1
    , input signed [63:0] eta_0_1_2
    , input signed [63:0] eta_0_1_3
    , input signed [63:0] eta_0_1_4
    , input signed [63:0] eta_0_1_5
    , input signed [63:0] eta_0_1_6
    , input signed [63:0] eta_0_1_7
    , input signed [63:0] eta_0_2_0
    , input signed [63:0] eta_0_2_1
    , input signed [63:0] eta_0_2_2
    , input signed [63:0] eta_0_2_3
    , input signed [63:0] eta_0_2_4
    , input signed [63:0] eta_0_2_5
    , input signed [63:0] eta_0_2_6
    , input signed [63:0] eta_0_2_7
    , input signed [63:0] eta_0_3_0
    , input signed [63:0] eta_0_3_1
    , input signed [63:0] eta_0_3_2
    , input signed [63:0] eta_0_3_3
    , input signed [63:0] eta_0_3_4
    , input signed [63:0] eta_0_3_5
    , input signed [63:0] eta_0_3_6
    , input signed [63:0] eta_0_3_7
    , input signed [63:0] eta_0_4_0
    , input signed [63:0] eta_0_4_1
    , input signed [63:0] eta_0_4_2
    , input signed [63:0] eta_0_4_3
    , input signed [63:0] eta_0_4_4
    , input signed [63:0] eta_0_4_5
    , input signed [63:0] eta_0_4_6
    , input signed [63:0] eta_0_4_7
    , input signed [63:0] eta_0_5_0
    , input signed [63:0] eta_0_5_1
    , input signed [63:0] eta_0_5_2
    , input signed [63:0] eta_0_5_3
    , input signed [63:0] eta_0_5_4
    , input signed [63:0] eta_0_5_5
    , input signed [63:0] eta_0_5_6
    , input signed [63:0] eta_0_5_7
    , input signed [63:0] eta_0_6_0
    , input signed [63:0] eta_0_6_1
    , input signed [63:0] eta_0_6_2
    , input signed [63:0] eta_0_6_3
    , input signed [63:0] eta_0_6_4
    , input signed [63:0] eta_0_6_5
    , input signed [63:0] eta_0_6_6
    , input signed [63:0] eta_0_6_7
    , input signed [63:0] eta_0_7_0
    , input signed [63:0] eta_0_7_1
    , input signed [63:0] eta_0_7_2
    , input signed [63:0] eta_0_7_3
    , input signed [63:0] eta_0_7_4
    , input signed [63:0] eta_0_7_5
    , input signed [63:0] eta_0_7_6
    , input signed [63:0] eta_0_7_7
    , input signed [63:0] eta_1_0_0
    , input signed [63:0] eta_1_0_1
    , input signed [63:0] eta_1_0_2
    , input signed [63:0] eta_1_0_3
    , input signed [63:0] eta_1_0_4
    , input signed [63:0] eta_1_0_5
    , input signed [63:0] eta_1_0_6
    , input signed [63:0] eta_1_0_7
    , input signed [63:0] eta_1_1_0
    , input signed [63:0] eta_1_1_1
    , input signed [63:0] eta_1_1_2
    , input signed [63:0] eta_1_1_3
    , input signed [63:0] eta_1_1_4
    , input signed [63:0] eta_1_1_5
    , input signed [63:0] eta_1_1_6
    , input signed [63:0] eta_1_1_7
    , input signed [63:0] eta_1_2_0
    , input signed [63:0] eta_1_2_1
    , input signed [63:0] eta_1_2_2
    , input signed [63:0] eta_1_2_3
    , input signed [63:0] eta_1_2_4
    , input signed [63:0] eta_1_2_5
    , input signed [63:0] eta_1_2_6
    , input signed [63:0] eta_1_2_7
    , input signed [63:0] eta_1_3_0
    , input signed [63:0] eta_1_3_1
    , input signed [63:0] eta_1_3_2
    , input signed [63:0] eta_1_3_3
    , input signed [63:0] eta_1_3_4
    , input signed [63:0] eta_1_3_5
    , input signed [63:0] eta_1_3_6
    , input signed [63:0] eta_1_3_7
    , input signed [63:0] eta_1_4_0
    , input signed [63:0] eta_1_4_1
    , input signed [63:0] eta_1_4_2
    , input signed [63:0] eta_1_4_3
    , input signed [63:0] eta_1_4_4
    , input signed [63:0] eta_1_4_5
    , input signed [63:0] eta_1_4_6
    , input signed [63:0] eta_1_4_7
    , input signed [63:0] eta_1_5_0
    , input signed [63:0] eta_1_5_1
    , input signed [63:0] eta_1_5_2
    , input signed [63:0] eta_1_5_3
    , input signed [63:0] eta_1_5_4
    , input signed [63:0] eta_1_5_5
    , input signed [63:0] eta_1_5_6
    , input signed [63:0] eta_1_5_7
    , input signed [63:0] eta_1_6_0
    , input signed [63:0] eta_1_6_1
    , input signed [63:0] eta_1_6_2
    , input signed [63:0] eta_1_6_3
    , input signed [63:0] eta_1_6_4
    , input signed [63:0] eta_1_6_5
    , input signed [63:0] eta_1_6_6
    , input signed [63:0] eta_1_6_7
    , input signed [63:0] eta_1_7_0
    , input signed [63:0] eta_1_7_1
    , input signed [63:0] eta_1_7_2
    , input signed [63:0] eta_1_7_3
    , input signed [63:0] eta_1_7_4
    , input signed [63:0] eta_1_7_5
    , input signed [63:0] eta_1_7_6
    , input signed [63:0] eta_1_7_7

      // Outputs
    , output wire signed [63:0] result_0_0
    , output wire signed [63:0] result_0_1
    , output wire signed [63:0] result_0_2
    , output wire signed [63:0] result_0_3
    , output wire signed [63:0] result_0_4
    , output wire signed [63:0] result_0_5
    , output wire signed [63:0] result_0_6
    , output wire signed [63:0] result_0_7
    , output wire signed [63:0] result_1_0
    , output wire signed [63:0] result_1_1
    , output wire signed [63:0] result_1_2
    , output wire signed [63:0] result_1_3
    , output wire signed [63:0] result_1_4
    , output wire signed [63:0] result_1_5
    , output wire signed [63:0] result_1_6
    , output wire signed [63:0] result_1_7
    , output wire signed [63:0] result_2_0
    , output wire signed [63:0] result_2_1
    , output wire signed [63:0] result_2_2
    , output wire signed [63:0] result_2_3
    , output wire signed [63:0] result_2_4
    , output wire signed [63:0] result_2_5
    , output wire signed [63:0] result_2_6
    , output wire signed [63:0] result_2_7
    , output wire signed [63:0] result_3_0
    , output wire signed [63:0] result_3_1
    , output wire signed [63:0] result_3_2
    , output wire signed [63:0] result_3_3
    , output wire signed [63:0] result_3_4
    , output wire signed [63:0] result_3_5
    , output wire signed [63:0] result_3_6
    , output wire signed [63:0] result_3_7
    , output wire signed [63:0] result_4_0
    , output wire signed [63:0] result_4_1
    , output wire signed [63:0] result_4_2
    , output wire signed [63:0] result_4_3
    , output wire signed [63:0] result_4_4
    , output wire signed [63:0] result_4_5
    , output wire signed [63:0] result_4_6
    , output wire signed [63:0] result_4_7
    , output wire signed [63:0] result_5_0
    , output wire signed [63:0] result_5_1
    , output wire signed [63:0] result_5_2
    , output wire signed [63:0] result_5_3
    , output wire signed [63:0] result_5_4
    , output wire signed [63:0] result_5_5
    , output wire signed [63:0] result_5_6
    , output wire signed [63:0] result_5_7
    , output wire signed [63:0] result_6_0
    , output wire signed [63:0] result_6_1
    , output wire signed [63:0] result_6_2
    , output wire signed [63:0] result_6_3
    , output wire signed [63:0] result_6_4
    , output wire signed [63:0] result_6_5
    , output wire signed [63:0] result_6_6
    , output wire signed [63:0] result_6_7
    , output wire signed [63:0] result_7_0
    , output wire signed [63:0] result_7_1
    , output wire signed [63:0] result_7_2
    , output wire signed [63:0] result_7_3
    , output wire signed [63:0] result_7_4
    , output wire signed [63:0] result_7_5
    , output wire signed [63:0] result_7_6
    , output wire signed [63:0] result_7_7
    );
  reg [4095:0] s1 = {{64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
  64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
              64'sd7,   64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,
                                    64'sd5,   64'sd6,   64'sd7,   64'sd8},
 {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
  64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
              64'sd7,   64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,
                                    64'sd5,   64'sd6,   64'sd7,   64'sd8},
 {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
  64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
              64'sd7,   64'sd8}};
  wire [4095:0] a;
  wire [4095:0] b;
  wire [4095:0] mBT;
  wire [4095:0] result_8;
  wire [8191:0] eta;
  wire [4095:0] result;
  wire [511:0] result_0;
  wire [511:0] result_1;
  wire [511:0] result_2;
  wire [511:0] result_3;
  wire [511:0] result_4;
  wire [511:0] result_5;
  wire [511:0] result_6;
  wire [511:0] result_7;

  assign eta = {{{eta_0_0_0,   eta_0_0_1,
                  eta_0_0_2,   eta_0_0_3,   eta_0_0_4,
                  eta_0_0_5,   eta_0_0_6,   eta_0_0_7},
                 {eta_0_1_0,   eta_0_1_1,   eta_0_1_2,
                  eta_0_1_3,   eta_0_1_4,   eta_0_1_5,
                  eta_0_1_6,   eta_0_1_7},   {eta_0_2_0,
                                              eta_0_2_1,   eta_0_2_2,   eta_0_2_3,
                                              eta_0_2_4,   eta_0_2_5,   eta_0_2_6,
                                              eta_0_2_7},   {eta_0_3_0,   eta_0_3_1,
                                                             eta_0_3_2,   eta_0_3_3,   eta_0_3_4,
                                                             eta_0_3_5,   eta_0_3_6,   eta_0_3_7},
                 {eta_0_4_0,   eta_0_4_1,   eta_0_4_2,
                  eta_0_4_3,   eta_0_4_4,   eta_0_4_5,
                  eta_0_4_6,   eta_0_4_7},   {eta_0_5_0,
                                              eta_0_5_1,   eta_0_5_2,   eta_0_5_3,
                                              eta_0_5_4,   eta_0_5_5,   eta_0_5_6,
                                              eta_0_5_7},   {eta_0_6_0,   eta_0_6_1,
                                                             eta_0_6_2,   eta_0_6_3,   eta_0_6_4,
                                                             eta_0_6_5,   eta_0_6_6,   eta_0_6_7},
                 {eta_0_7_0,   eta_0_7_1,   eta_0_7_2,
                  eta_0_7_3,   eta_0_7_4,   eta_0_7_5,
                  eta_0_7_6,   eta_0_7_7}},   {{eta_1_0_0,
                                                eta_1_0_1,   eta_1_0_2,   eta_1_0_3,
                                                eta_1_0_4,   eta_1_0_5,   eta_1_0_6,
                                                eta_1_0_7},   {eta_1_1_0,   eta_1_1_1,
                                                               eta_1_1_2,   eta_1_1_3,   eta_1_1_4,
                                                               eta_1_1_5,   eta_1_1_6,   eta_1_1_7},
                                               {eta_1_2_0,   eta_1_2_1,   eta_1_2_2,
                                                eta_1_2_3,   eta_1_2_4,   eta_1_2_5,
                                                eta_1_2_6,   eta_1_2_7},   {eta_1_3_0,
                                                                            eta_1_3_1,   eta_1_3_2,   eta_1_3_3,
                                                                            eta_1_3_4,   eta_1_3_5,   eta_1_3_6,
                                                                            eta_1_3_7},   {eta_1_4_0,   eta_1_4_1,
                                                                                           eta_1_4_2,   eta_1_4_3,
                                                                                           eta_1_4_4,   eta_1_4_5,
                                                                                           eta_1_4_6,   eta_1_4_7},
                                               {eta_1_5_0,   eta_1_5_1,   eta_1_5_2,
                                                eta_1_5_3,   eta_1_5_4,   eta_1_5_5,
                                                eta_1_5_6,   eta_1_5_7},   {eta_1_6_0,
                                                                            eta_1_6_1,   eta_1_6_2,   eta_1_6_3,
                                                                            eta_1_6_4,   eta_1_6_5,   eta_1_6_6,
                                                                            eta_1_6_7},   {eta_1_7_0,   eta_1_7_1,
                                                                                           eta_1_7_2,   eta_1_7_3,
                                                                                           eta_1_7_4,   eta_1_7_5,
                                                                                           eta_1_7_6,   eta_1_7_7}}};

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_register
    if ( rst) begin
      s1 <= {{64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
    64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
                64'sd7,   64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,
                                      64'sd5,   64'sd6,   64'sd7,   64'sd8},
   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
    64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
                64'sd7,   64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,
                                      64'sd5,   64'sd6,   64'sd7,   64'sd8},
   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,   64'sd7,
    64'sd8},   {64'sd1,   64'sd2,   64'sd3,   64'sd4,   64'sd5,   64'sd6,
                64'sd7,   64'sd8}};
    end else if (en) begin
      s1 <= result_8;
    end
  end
  // register end

  assign a = eta[8191:4096];

  assign b = eta[4095:0];

  // transpose begin
  genvar row_index;
  genvar col_index;
  generate
  for (row_index = 0; row_index < 8; row_index = row_index + 1) begin : transpose_outer
    for (col_index = 0; col_index < 8; col_index = col_index + 1) begin : transpose_inner
      assign mBT[((col_index*512)+(row_index*64))+:64] = b[((row_index*512)+(col_index*64))+:64];
    end
  end
  endgenerate
  // transpose end

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 8; i_1 = i_1 + 1) begin : map_0
    wire [511:0] map_in_0;
    assign map_in_0 = a[i_1*512+:512];
    wire [511:0] map_out_0;
    wire [511:0] c$bb_res_res;
    // map begin
    genvar i_0;

    for (i_0=0; i_0 < 8; i_0 = i_0 + 1) begin : map
      wire [511:0] map_in;
      assign map_in = mBT[i_0*512+:512];
      wire signed [63:0] map_out;
      wire [511:0] c$app_arg;
    wire signed [63:0] result_9;
    assign map_out = result_9;

    // zipWith start
    genvar i;

    for (i = 0; i < 8; i = i + 1) begin : zipWith
      wire signed [63:0] zipWith_in1;
      assign zipWith_in1 = map_in_0[i*64+:64];
      wire signed [63:0] zipWith_in2;
      assign zipWith_in2 = map_in[i*64+:64];
      wire signed [63:0] c$n;
      wire signed [63:0] x;
    wire signed [63:0] y;
    wire signed [63:0] c$case_alt;
    assign c$n = c$case_alt;

    assign x = zipWith_in1;

    assign y = zipWith_in2;

    assign c$case_alt = x * y;


      assign c$app_arg[i*64+:64] = c$n;
    end

    // zipWith end

    wire [511:0] vec;
    wire signed [63:0] acc_3_0;
    wire signed [63:0] acc_1;
    wire signed [63:0] acc_2;
    wire signed [63:0] acc_3;
    wire signed [63:0] acc_4;
    wire signed [63:0] acc_5;
    wire signed [63:0] acc_6;
    wire signed [63:0] acc_7;
    wire signed [63:0] acc_8;
    wire signed [63:0] acc_1_0;
    wire signed [63:0] acc_1_1;
    wire signed [63:0] acc_1_2;
    wire signed [63:0] acc_1_3;
    wire signed [63:0] acc_2_0;
    wire signed [63:0] acc_2_1;
    assign result_9 = acc_3_0;

    assign vec = c$app_arg;

    assign acc_1 = $signed(vec[511:448]);

    assign acc_2 = $signed(vec[447:384]);

    assign acc_3 = $signed(vec[383:320]);

    assign acc_4 = $signed(vec[319:256]);

    assign acc_5 = $signed(vec[255:192]);

    assign acc_6 = $signed(vec[191:128]);

    assign acc_7 = $signed(vec[127:64]);

    assign acc_8 = $signed(vec[63:0]);

    wire signed [63:0] x_1;
    wire signed [63:0] y_1;
    wire signed [63:0] c$case_alt_1;
    assign acc_1_0 = c$case_alt_1;

    assign x_1 = acc_1;

    assign y_1 = acc_2;

    assign c$case_alt_1 = x_1 + y_1;



    wire signed [63:0] x_2;
    wire signed [63:0] y_2;
    wire signed [63:0] c$case_alt_2;
    assign acc_1_1 = c$case_alt_2;

    assign x_2 = acc_3;

    assign y_2 = acc_4;

    assign c$case_alt_2 = x_2 + y_2;



    wire signed [63:0] x_3;
    wire signed [63:0] y_3;
    wire signed [63:0] c$case_alt_3;
    assign acc_1_2 = c$case_alt_3;

    assign x_3 = acc_5;

    assign y_3 = acc_6;

    assign c$case_alt_3 = x_3 + y_3;



    wire signed [63:0] x_4;
    wire signed [63:0] y_4;
    wire signed [63:0] c$case_alt_4;
    assign acc_1_3 = c$case_alt_4;

    assign x_4 = acc_7;

    assign y_4 = acc_8;

    assign c$case_alt_4 = x_4 + y_4;



    wire signed [63:0] x_5;
    wire signed [63:0] y_5;
    wire signed [63:0] c$case_alt_5;
    assign acc_2_0 = c$case_alt_5;

    assign x_5 = acc_1_0;

    assign y_5 = acc_1_1;

    assign c$case_alt_5 = x_5 + y_5;



    wire signed [63:0] x_6;
    wire signed [63:0] y_6;
    wire signed [63:0] c$case_alt_6;
    assign acc_2_1 = c$case_alt_6;

    assign x_6 = acc_1_2;

    assign y_6 = acc_1_3;

    assign c$case_alt_6 = x_6 + y_6;



    wire signed [63:0] x_7;
    wire signed [63:0] y_7;
    wire signed [63:0] c$case_alt_7;
    assign acc_3_0 = c$case_alt_7;

    assign x_7 = acc_2_0;

    assign y_7 = acc_2_1;

    assign c$case_alt_7 = x_7 + y_7;






      assign c$bb_res_res[i_0*64+:64] = map_out;
    end

    // map end

    assign map_out_0 = c$bb_res_res;


    assign result_8[i_1*512+:512] = map_out_0;
  end
  endgenerate
  // map end

  assign result = s1;

  assign result_0 = result[4095:3584];

  assign result_1 = result[3583:3072];

  assign result_2 = result[3071:2560];

  assign result_3 = result[2559:2048];

  assign result_4 = result[2047:1536];

  assign result_5 = result[1535:1024];

  assign result_6 = result[1023:512];

  assign result_7 = result[511:0];

  assign result_0_0 = $signed(result_0[511:448]);

  assign result_0_1 = $signed(result_0[447:384]);

  assign result_0_2 = $signed(result_0[383:320]);

  assign result_0_3 = $signed(result_0[319:256]);

  assign result_0_4 = $signed(result_0[255:192]);

  assign result_0_5 = $signed(result_0[191:128]);

  assign result_0_6 = $signed(result_0[127:64]);

  assign result_0_7 = $signed(result_0[63:0]);

  assign result_1_0 = $signed(result_1[511:448]);

  assign result_1_1 = $signed(result_1[447:384]);

  assign result_1_2 = $signed(result_1[383:320]);

  assign result_1_3 = $signed(result_1[319:256]);

  assign result_1_4 = $signed(result_1[255:192]);

  assign result_1_5 = $signed(result_1[191:128]);

  assign result_1_6 = $signed(result_1[127:64]);

  assign result_1_7 = $signed(result_1[63:0]);

  assign result_2_0 = $signed(result_2[511:448]);

  assign result_2_1 = $signed(result_2[447:384]);

  assign result_2_2 = $signed(result_2[383:320]);

  assign result_2_3 = $signed(result_2[319:256]);

  assign result_2_4 = $signed(result_2[255:192]);

  assign result_2_5 = $signed(result_2[191:128]);

  assign result_2_6 = $signed(result_2[127:64]);

  assign result_2_7 = $signed(result_2[63:0]);

  assign result_3_0 = $signed(result_3[511:448]);

  assign result_3_1 = $signed(result_3[447:384]);

  assign result_3_2 = $signed(result_3[383:320]);

  assign result_3_3 = $signed(result_3[319:256]);

  assign result_3_4 = $signed(result_3[255:192]);

  assign result_3_5 = $signed(result_3[191:128]);

  assign result_3_6 = $signed(result_3[127:64]);

  assign result_3_7 = $signed(result_3[63:0]);

  assign result_4_0 = $signed(result_4[511:448]);

  assign result_4_1 = $signed(result_4[447:384]);

  assign result_4_2 = $signed(result_4[383:320]);

  assign result_4_3 = $signed(result_4[319:256]);

  assign result_4_4 = $signed(result_4[255:192]);

  assign result_4_5 = $signed(result_4[191:128]);

  assign result_4_6 = $signed(result_4[127:64]);

  assign result_4_7 = $signed(result_4[63:0]);

  assign result_5_0 = $signed(result_5[511:448]);

  assign result_5_1 = $signed(result_5[447:384]);

  assign result_5_2 = $signed(result_5[383:320]);

  assign result_5_3 = $signed(result_5[319:256]);

  assign result_5_4 = $signed(result_5[255:192]);

  assign result_5_5 = $signed(result_5[191:128]);

  assign result_5_6 = $signed(result_5[127:64]);

  assign result_5_7 = $signed(result_5[63:0]);

  assign result_6_0 = $signed(result_6[511:448]);

  assign result_6_1 = $signed(result_6[447:384]);

  assign result_6_2 = $signed(result_6[383:320]);

  assign result_6_3 = $signed(result_6[319:256]);

  assign result_6_4 = $signed(result_6[255:192]);

  assign result_6_5 = $signed(result_6[191:128]);

  assign result_6_6 = $signed(result_6[127:64]);

  assign result_6_7 = $signed(result_6[63:0]);

  assign result_7_0 = $signed(result_7[511:448]);

  assign result_7_1 = $signed(result_7[447:384]);

  assign result_7_2 = $signed(result_7[383:320]);

  assign result_7_3 = $signed(result_7[319:256]);

  assign result_7_4 = $signed(result_7[255:192]);

  assign result_7_5 = $signed(result_7[191:128]);

  assign result_7_6 = $signed(result_7[127:64]);

  assign result_7_7 = $signed(result_7[63:0]);


endmodule

